### ISSUE TITLE
theme_matplotlib([...], matplotlib_defaults=False) doesn't work

### ISSUE THREAD

**Issue by jankatins** [yhat/ggpy#139]
Using `theme_matplotlib(rc={"figure.figsize":"11, 11"}, matplotlib_defaults=False)` will reset the plot defaults to the matplotlib ones. This is because this is a "partial" update and the default `theme_grey()` should also be applied but isn't.

the current fix is to apply `+ theme_grey() + theme_matplotlib(...)`

-> This needs "partial" support as ggplot2 has: if a theme with 'partial' is added, the default should still be applied first.

**Comment by martinbel** [comment]
I've just installed the github version and I'm not even having theme_matplotlib() available. 

```
In [1]: from ggplot import *
In [2]: theme_matplotlib
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-7c0914d801a3> in <module>()
----> 1 theme_matplotlib
NameError: name 'theme_matplotlib' is not defined
```
