### ISSUE TITLE
Implement stats for geom_bar

### ISSUE THREAD

**Issue by jankatins** [yhat/ggpy#152]
Basically everything apart from counting the number of occurences (`stat="bin"`) doesn't yet work.

It would be nice if at least `stat = "identity"`would be available: 

> [from the ggplot2 doumentation: http://docs.ggplot2.org/0.9.3.1/geom_bar.html]
> If you want the heights of the bars to represent values in the data, use stat="identity" and map a value to the y aesthetic.

**Comment by Rich1000** [comment]
+1 from me too, `stat = "identity"` would be amazing.

**Comment by maxgrenderjones** [comment]
If nothing else, it would be great if the [docs](http://ggplot.yhathq.com/docs/geom_bar.html) didn't make it look like it works (it even shows the default as `stat='identity'` not `'bin'`). Likely a quicker fix than actually making it work :smile: 

Was super confused for a while
