### ISSUE TITLE
scale_size is missing

### ISSUE THREAD

**Issue by jankatins** [yhat/ggpy#159]
Currently there is no way to change the size of geom_point() without changeing the legend as well (i.e. changing the input values for the size mapping)

http://docs.ggplot2.org/current/scale_size.html

**Comment by wanglongqi** [comment]
+1, it seems this project is not under active development since last year.

**Comment by has2k1** [comment]
@wanglongqi, PR #360 is the future.

**Comment by wanglongqi** [comment]
@has2k1 Good job! Looking forward for merging of the PR.
