### ISSUE TITLE
Rename to pygplot or similar

### ISSUE THREAD

**Issue by hadley** [yhat/ggpy#537]
It's just too confusing having a completely independent package with the same name.

**Comment by beltashazzer** [comment]
This does sound reasonable.  It would make googling more specific too.

**Comment by hadley** [comment]
I don't want to be a dick about this, but I think it's bad form to re-use an existing package name.

**Comment by TyberiusPrime** [comment]
I must aggree with hadley on this.
Keep in mind that there's already a pyggplot which is a wrapper for ggplot2.

**Comment by setempler** [comment]
Waste of time for everybody.

If so, I suggest *ggpython*.

Is there even a TM? Can people not distinguish syntax 'import ggplot' from 'library(ggplot2)'?

**Comment by TyberiusPrime** [comment]
Point is: you want the search engines to be able to differentiate. Vastly easier if you have two distinct names. Searching for +python or +R (stupid one letter language names...) isn't as specific.

**Comment by hadley** [comment]
@setempler stealing other people's names is generally considered to be rude

**Comment by setempler** [comment]
@hadley that's life. Not a legal issue. On the other, calling it stealing can occur rude, too. But what's *important* is: it is unnecessary work if you have implemented the syntax already into production.

@TyberiusPrime that's R's 'fault', then? ;)

**Comment by TyberiusPrime** [comment]
Changing 'import ggplot' to 'import ggpython as ggplot' seems to me to be a straight forward change and not too much work to use a newer version.
 
Hadley has a huge user base - and therefore a big support load, and I assume he'd be unwilling to support python users dropping questions in the R channels because the name is the same. Which will happen if this package builds traction.

**Comment by hadley** [comment]
@setempler I never claimed it was a legal issue. If someone wants to steal my package name, I'm totally within my rights to complain about it.

**Comment by richierocks** [comment]
Suggested alternative name: `"pyggyback"`.

**Comment by glamp** [comment]
Issue has been resolved.

**Comment by hadley** [comment]
Great, thanks!

**Comment by yoavram** [comment]
Fix`README.md`?

**Comment by setempler** [comment]
Fix fix? #585 https://pypi.python.org/pypi/ggpy

**Comment by DSLituiev** [comment]
the link in https://pypi.python.org/pypi/ggpy (http://github.com/premisedata/ggpy) seems pointing nowhere. Can name be reclaimed with pypi ?

**Comment by naught101** [comment]
https://github.com/paleolimbot/ggpy
