### ISSUE TITLE
Color on geom area isn't working

### ISSUE THREAD

**Issue by sbstnzmr** [yhat/ggpy#587]
The legend has color, the area chart ist black.

**Comment by ChickenProp** [comment]
If you're using `aes(color=...)`, have you tried `aes(fill=...)` instead?

**Comment by sbstnzmr** [comment]
Yes, I'm translating an existing R project for my first time use with Pythons ggplot. It's amazing with how little work this could be done. Though there are some things not working. However this is something I can't reproduce.

Also the `geom_area(position = 'stack')` doesn't change anything. Not sure if an issue though or just different than R. And I can't call the color/fill from the `geom_whatever()` but have to do it from `ggplot()`'s `aes()`. 

edit:
After further testing I'll just close it because I can't reproduce the error.
