### ISSUE TITLE
ggplot does not show graphics

### ISSUE THREAD

**Issue by zhanxw** [yhat/ggpy#59]
Hello, 

I am using Python 2.7.5 in Linux.
Just tried the example code.
Instead of getting a graph, I got "<ggplot: (3297489)>" as outputs.
Is there a way I can debug and fix this problem?

Thanks.

Python 2.7.5 (default, May 25 2013, 00:17:53)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from ggplot import *
> > > 
> > > print ggplot(mtcars, aes('mpg', 'qsec')) + \
> > > ...   geom_point(colour='steelblue') + \
> > > ...   scale_x_continuous(breaks=[10,20,30],  \
> > > ...                      labels=["horrible", "ok", "awesome"])
> > > <ggplot: (3297489)>

**Comment by yyl** [comment]
So this issue could only be solved by reinstalling from source? Cause `pot.show(1)` after `print` does not work for me.
