### ISSUE TITLE
Is this project still under development?

### ISSUE THREAD

**Issue by MarcoMuellner** [yhat/ggpy#619]
As title says. It is a brilliant project and it would be sad to see it die off. There are already quite some bugs/missing documentation or deprecations (pandas!). There are pull requests which are were opened in January!

**Comment by shoyer** [comment]
Take a look at plotnine, which was originally forked from ggpy (now mostly rewritten):
https://github.com/has2k1/plotnine

**Comment by r-barnes** [comment]
plotnine seems to be working well!
