### ISSUE TITLE
Looking for `ggplot` substitution

### ISSUE THREAD

**Issue by botbw** [yhat/ggpy#679]
Hi I'm working on a project using `ggplot`. 

It seems this repo hasn't been updated for years, and many modules/functions used have been deprecated (For example, the `pandas` import error). 

Would like to know if there is any "API-wise" substitution lib for `gglot` so I can do something like `import XXX as ggplot`

**Comment by DesmondChoy** [comment]
Try [plotnine](https://github.com/has2k1/plotnine) - it has a very similar syntax.

**Comment by botbw** [comment]
> Try [plotnine](https://github.com/has2k1/plotnine) - it has a very similar syntax.

Thanks Desmond, I'll have a look!
