### ISSUE TITLE
How can I change figure size?

### ISSUE THREAD

**Issue by eduardflorinescu** [yhat/ggpy#95]
If I try to set the figure size before, it creates the plot on figure 2, if I set the figure size on figure 2 to creates the plot on figure 3, etc

If this doesn't work:  

``` python
plt.figure(num=1, figsize=(16, 10))
```

How can I change the figure size of the ggplot chart?

**Comment by Vageshwari** [comment]
When I print to a file , the size does not change. It remains same as original. Any way to control it?

**Comment by DSLituiev** [comment]
I was able to control the size of the figure by setting `theme(plot_margin=...)`:

    ggplot(df,aes('x','y')) + geom_line() + theme(plot_margin = dict(right = 15, top=10))

How about implementing an alternative `plot_margin` as tuple of two `(width, height)` ?

**Comment by grauscher** [comment]
Another solution, if you don't want to alter matplotlib's configuration:

```python
from ggplot import *
from matplotlib import pyplot as plt

p = (ggplot(diamonds,
          aes(x='x', y='y', color='cut', fill='cut')) +
     geom_point() +
     facet_wrap(x='cut'))

# This command "renders" the figure and creates the attribute `fig` on the p object
p.make()

# Then you can alter its properties
p.fig.set_size_inches(15, 5, forward=True)
p.fig.set_dpi(100)
p.fig

# And display the final figure
plt.show()
```
